/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: faradeyko (https://sketchfab.com/faradeyko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maslow-pyramyd-of-needs-43e530c69f0b4fb98e1763ae0bfb1f81
Title: Maslow Pyramyd Of Needs
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Material.018']}
        position={[0, 2.53, 0]}
        scale={[3.525, 2.518, 3.525]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials['Material.019']}
        position={[0, 3.971, 0.883]}
        rotation={[0.995, 0, 0]}
        scale={0.215}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials['Material.019']}
        position={[0, 3.094, 1.47]}
        rotation={[0.995, 0, 0]}
        scale={0.318}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials['Material.019']}
        position={[0, 2.3, 2]}
        rotation={[0.995, 0, 0]}
        scale={0.337}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials['Material.019']}
        position={[0, 1.306, 2.66]}
        rotation={[0.995, 0, 0]}
        scale={0.504}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials['Material.019']}
        position={[0, 0.311, 3.32]}
        rotation={[0.995, 0, 0]}
        scale={0.61}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials['Material.019']}
        position={[-3.26, 0.421, 0]}
        rotation={[Math.PI / 2, -0.576, Math.PI / 2]}
        scale={0.359}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials['Material.019']}
        position={[-2.585, 1.421, 0]}
        rotation={[Math.PI / 2, -0.576, Math.PI / 2]}
        scale={0.215}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials['Material.019']}
        position={[-1.92, 2.421, 0]}
        rotation={[Math.PI / 2, -0.576, Math.PI / 2]}
        scale={0.197}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials['Material.019']}
        position={[-1.29, 3.362, 0]}
        rotation={[Math.PI / 2, -0.576, Math.PI / 2]}
        scale={0.18}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials['Material.019']}
        position={[-0.586, 4.419, 0]}
        rotation={[Math.PI / 2, -0.576, Math.PI / 2]}
        scale={0.172}
      />
    </group>
  );
}

useGLTF.preload('/scene.gltf');
